version: "2"

checks:
  argument-count:
    enabled: false
  complex-logic:
    enabled: false
  file-lines:
    enabled: false
  method-complexity:
    enabled: false
  method-count:
    enabled: false
  method-lines:
    enabled: false
  nested-control-flow:
    enabled: false
  return-statements:
    enabled: false
  similar-code:
    enabled: false
  identical-code:
    enabled: false

plugins:
  duplication:
    enabled: false
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    channel: "eslint-7"
  fixme:
    enabled: true

exclude_paths:
- test/
- dev/
- docs/
- benchmark/
- examples/
- typings/
